# syntax=docker/dockerfile:1

ARG NODE_VERSION=18.18.0
ARG PNPM_VERSION=8.6.12

FROM node:${NODE_VERSION}-alpine

# ENV NODE_ENV production

# Install pnpm.
RUN --mount=type=cache,target=/root/.npm \
    npm install -g pnpm@${PNPM_VERSION}

WORKDIR /usr/src/app

RUN --mount=type=bind,source=package.json,target=package.json \
    --mount=type=bind,source=pnpm-lock.yaml,target=pnpm-lock.yaml \
    --mount=type=cache,target=/root/.local/share/pnpm/store \
    pnpm install --frozen-lockfile
    # pnpm install --prod --frozen-lockfile

# USER node

COPY . .

EXPOSE 8000

CMD pnpm dev
